-- mods/default/aliases.lua

-- Aliases to support loading worlds using nodes following the old naming convention
-- These can also be helpful when using chat commands, for example /giveme
minetest.register_alias("stone", "blocklife:stone")
minetest.register_alias("stone_with_coal", "blocklife:stone_with_coal")
minetest.register_alias("stone_with_iron", "blocklife:stone_with_iron")
minetest.register_alias("dirt_with_grass", "blocklife:dirt_with_grass")
minetest.register_alias("dirt_with_grass_footsteps", "blocklife:dirt_with_grass_footsteps")
minetest.register_alias("dirt", "blocklife:dirt")
minetest.register_alias("sand", "blocklife:sand")
minetest.register_alias("gravel", "blocklife:gravel")
minetest.register_alias("sandstone", "blocklife:sandstone")
minetest.register_alias("clay", "blocklife:clay")
minetest.register_alias("brick", "blocklife:brick")
minetest.register_alias("tree", "blocklife:tree")
minetest.register_alias("leaves", "blocklife:leaves")
minetest.register_alias("cactus", "blocklife:cactus")
minetest.register_alias("papyrus", "blocklife:papyrus")
minetest.register_alias("bookshelf", "blocklife:bookshelf")
minetest.register_alias("glass", "blocklife:glass")
minetest.register_alias("wooden_fence", "blocklife:fence_wood")
minetest.register_alias("rail", "carts:rail")
minetest.register_alias("ladder", "blocklife:ladder_wood")
minetest.register_alias("wood", "blocklife:wood")
minetest.register_alias("mese", "blocklife:mese")
minetest.register_alias("cloud", "blocklife:cloud")
minetest.register_alias("water_flowing", "blocklife:water_flowing")
minetest.register_alias("water_source", "blocklife:water_source")
minetest.register_alias("lava_flowing", "blocklife:lava_flowing")
minetest.register_alias("lava_source", "blocklife:lava_source")
minetest.register_alias("torch", "blocklife:torch")
minetest.register_alias("sign_wall", "blocklife:sign_wall_wood")
minetest.register_alias("furnace", "blocklife:furnace")
minetest.register_alias("chest", "blocklife:chest")
minetest.register_alias("locked_chest", "blocklife:chest_locked")
minetest.register_alias("cobble", "blocklife:cobble")
minetest.register_alias("mossycobble", "blocklife:mossycobble")
minetest.register_alias("steelblock", "blocklife:steelblock")
minetest.register_alias("sapling", "blocklife:sapling")
minetest.register_alias("apple", "blocklife:apple")

minetest.register_alias("WPick", "blocklife:pick_wood")
minetest.register_alias("STPick", "blocklife:pick_stone")
minetest.register_alias("SteelPick", "blocklife:pick_steel")
minetest.register_alias("MesePick", "blocklife:pick_mese")
minetest.register_alias("WShovel", "blocklife:shovel_wood")
minetest.register_alias("STShovel", "blocklife:shovel_stone")
minetest.register_alias("SteelShovel", "blocklife:shovel_steel")
minetest.register_alias("WAxe", "blocklife:axe_wood")
minetest.register_alias("STAxe", "blocklife:axe_stone")
minetest.register_alias("SteelAxe", "blocklife:axe_steel")
minetest.register_alias("WSword", "blocklife:sword_wood")
minetest.register_alias("STSword", "blocklife:sword_stone")
minetest.register_alias("SteelSword", "blocklife:sword_steel")

minetest.register_alias("Stick", "blocklife:stick")
minetest.register_alias("paper", "blocklife:paper")
minetest.register_alias("book", "blocklife:book")
minetest.register_alias("lump_of_coal", "blocklife:coal_lump")
minetest.register_alias("lump_of_iron", "blocklife:iron_lump")
minetest.register_alias("lump_of_clay", "blocklife:clay_lump")
minetest.register_alias("steel_ingot", "blocklife:steel_ingot")
minetest.register_alias("clay_brick", "blocklife:clay_brick")
minetest.register_alias("snow", "blocklife:snow")

-- 'mese_block' was used for a while for the block form of mese
minetest.register_alias("blocklife:mese_block", "blocklife:mese")


minetest.register_alias("blocklife:ladder", "blocklife:ladder_wood")
minetest.register_alias("blocklife:sign_wall", "blocklife:sign_wall_wood")
